# Set this website's info
# Change "coffeebank" to your GitHub username
# Change "moonrise" to your repository name
url: "https://MemeMC-Network.github.io"
baseurl: "/home"
siteIcon: /media/android-chrome-192x192.png
siteYear: 2023
siteFooterlink: /about
showinSearchEngines: true
# googleAnalyticsID: (uncomment to use)


# Set basic server info
serverName: MemeMC Network
serverDescription: MemeMC - Bedwars, PVP Practice, and more to come!
serverIP: mememc.club
useBedrockForOnlineStatus: false


# Discord information
discordInvite: https://discord.gg/V3SAX9udFF
discordServerID: 1089573156815122472
discordChannelID: 1125480774121046038


# # Navbar Links at the top of the page (uncomment "siteNav" to use)
# #   name - The title on the navbar
# #   url - The link it should go to (for example, if you have "maps.md" file, put "maps")
# #   newtab - Whether link should open in new tab
# 
# siteNav:
#   - name: MemeMC Network
#   - name: About
#     url: about


# Don't change anything below here, these are defaults set by GitHub Pages:
# ======
theme: minima
# plugins:
#   - jekyll-feed
# exclude:
#   - .sass-cache/
#   - .jekyll-cache/
#   - gemfiles/
#   - Gemfile
#   - Gemfile.lock
#   - node_modules/
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/